mixed-port: 7890
mode: rule
proxies:
- type: vless
  server: 2.26.255.206
  port: 443
  uuid: d9d0f208-d582-41d5-bb7b-742671402810
  udp: true
  flow: xtls-rprx-vision
  tls: true
  servername: eu-central-pl-1.hanvpn.biz
  client-fingerprint: edge
  reality-opts:
    public-key: NjIuu35vz5MthSzqd6kt8PbXbZxCCL2Rb2GbpMCRTEY
    short-id: 12e3b7681806bc97
  network: tcp
  _source_name: tg:VlessForU
  name: Россия 1
- type: vless
  server: 143.246.182.63
  port: 443
  uuid: 5b45355f-1a9c-4802-90ed-0d1f5dcd4562
  udp: true
  encryption: none
  tls: true
  servername: uk10.filesnap.tech
  client-fingerprint: edge
  alpn:
  - http/1.1
  - h2
  skip-cert-verify: false
  network: xhttp
  xhttp-opts:
    path: /assets/build/_app/immutable/chunks/stream-one/
    host: uk10.filesnap.tech
  _source_name: Бесплатный
  name: Финляндия 1
- type: vless
  server: 194.87.52.142
  port: 443
  uuid: 8c9a8787-056f-4b47-b193-0dcfa273d825
  udp: true
  encryption: none
  flow: xtls-rprx-vision
  tls: true
  servername: ads.x5.ru
  client-fingerprint: firefox
  reality-opts:
    public-key: zRVSRinqebogFvlL5GWcaYfLlKGueXknigEI-f-tKAI
    short-id: d82c4b67f9a13e5c
  network: tcp
  _source_name: SNi
  name: Россия 2
- type: vless
  server: viper-21.moriarty-web.com
  port: 443
  uuid: cd3bb7d9-7df3-4644-ac05-c260990ac277
  udp: true
  flow: xtls-rprx-vision
  tls: true
  servername: viper-21.moriarty-web.com
  client-fingerprint: firefox
  network: tcp
  _source_name: Бесплатный
  name: Европа 1
- type: vless
  server: 50.7.249.170
  port: 443
  uuid: cd3bb7d9-7df3-4644-ac05-c260990ac277
  udp: true
  encryption: none
  flow: xtls-rprx-vision
  tls: true
  servername: pl1-ded.moritech.net
  client-fingerprint: firefox
  alpn:
  - h2
  network: tcp
  _source_name: Бесплатный
  name: Германия 1
- type: vless
  server: 144.31.28.104
  port: 8443
  uuid: 8c9a8787-056f-4b47-b193-0dcfa273d825
  udp: true
  encryption: none
  flow: xtls-rprx-vision
  tls: true
  servername: ads.x5.ru
  client-fingerprint: firefox
  reality-opts:
    public-key: zRVSRinqebogFvlL5GWcaYfLlKGueXknigEI-f-tKAI
    short-id: d82c4b67f9a13e5c
  network: tcp
  _source_name: SNi
  name: Россия 3
- type: vless
  server: de2.routeliora.ru
  port: 8443
  uuid: 70d482eb-7584-4841-a02a-c668f1ee33e7
  udp: true
  encryption: none
  flow: xtls-rprx-vision
  tls: true
  servername: de2.routeliora.ru
  client-fingerprint: firefox
  reality-opts:
    public-key: bDDR3ubmqiA8nv8uD72QLIKgpcWaENtY0Vumrce6jgg
    short-id: 9f3a7c2d
  network: tcp
  tcp-opts:
    header:
      type: none
  _source_name: Бесплатный
  name: Германия 2
- type: vless
  server: eu-central-pl-1.hanvpn.biz
  port: 443
  uuid: d9d0f208-d582-41d5-bb7b-742671402810
  udp: true
  flow: xtls-rprx-vision
  tls: true
  servername: eu-central-pl-1.hanvpn.biz
  client-fingerprint: firefox
  reality-opts:
    public-key: NjIuu35vz5MthSzqd6kt8PbXbZxCCL2Rb2GbpMCRTEY
    short-id: 12e3b7681806bc97
  network: tcp
  tcp-opts:
    header:
      type: none
  _source_name: Бесплатный
  name: Польша 1
- type: vless
  server: 50.7.245.35
  port: 443
  uuid: 5d4a87fa-16f1-4b65-b217-225a31e36239
  udp: true
  flow: xtls-rprx-vision
  tls: true
  servername: fr.convert-flow.net
  client-fingerprint: firefox
  reality-opts:
    public-key: 8ZYjmjb0b2QJKCGMrcdhQNV28jZZPCKgIQbIdqChQ0w
    short-id: 00a61d55a07de885
  network: tcp
  _source_name: Бесплатный
  name: Франция 1
- type: vless
  server: 194.34.175.66
  port: 443
  uuid: 6429d27e-a7d4-4e04-ae57-e88243fbbfe3
  udp: true
  encryption: none
  flow: xtls-rprx-vision
  tls: true
  servername: localhost
  client-fingerprint: firefox
  reality-opts:
    public-key: F2VfBr2UmjDTErB_oruvW5aIvzH_xGfM2AW5_w-DF0I
  network: tcp
  _source_name: Бесплатный
  name: Канада 1
- type: vless
  server: 132.243.228.209
  port: 8443
  uuid: 70d482eb-7584-4841-a02a-c668f1ee33e7
  udp: true
  flow: xtls-rprx-vision
  tls: true
  servername: de2.routeliora.ru
  client-fingerprint: firefox
  reality-opts:
    public-key: bDDR3ubmqiA8nv8uD72QLIKgpcWaENtY0Vumrce6jgg
    short-id: 9f3a7c2d
  network: tcp
  _source_name: Бесплатный
  name: Германия 3
- type: vless
  server: 194.34.175.123
  port: 443
  uuid: 6429d27e-a7d4-4e04-ae57-e88243fbbfe3
  udp: true
  encryption: none
  flow: xtls-rprx-vision
  tls: true
  servername: localhost
  client-fingerprint: firefox
  reality-opts:
    public-key: F2VfBr2UmjDTErB_oruvW5aIvzH_xGfM2AW5_w-DF0I
  network: tcp
  _source_name: Бесплатный
  name: Канада 2
- type: vless
  server: 50.7.248.234
  port: 443
  uuid: cd3bb7d9-7df3-4644-ac05-c260990ac277
  udp: true
  flow: xtls-rprx-vision
  tls: true
  servername: viper-22.moriarty-web.com
  client-fingerprint: firefox
  alpn:
  - h2
  network: tcp
  tcp-opts:
    header:
      type: none
  _source_name: Бесплатный
  name: Европа 2
- type: vless
  server: 138.16.141.59
  port: 7443
  uuid: a289a3d3-5833-4b28-8809-ae72898a98d0
  udp: true
  encryption: none
  tls: true
  servername: ibm.com
  client-fingerprint: firefox
  reality-opts:
    public-key: RY7zkFQ01lI92jxNAyCa8T33UBW1fgpJgg8ZEqMA10k
    short-id: a09ff9f8
  network: tcp
  _source_name: Бесплатный
  name: Европа 3
- type: vless
  server: 45.128.235.8
  port: 443
  uuid: d9d0f208-d582-41d5-bb7b-742671402810
  udp: true
  flow: xtls-rprx-vision
  tls: true
  servername: eu-north-fi-1.hanvpn.biz
  client-fingerprint: firefox
  reality-opts:
    public-key: nnkPnz6R86-6xG92s8k-1DUQPXAJIVMoMWDLPghh4x4
    short-id: 0173b2681806bc97
  network: tcp
  _source_name: Бесплатный
  name: Финляндия 2
- type: vless
  server: 138.124.183.18
  port: 443
  uuid: d9d0f208-d582-41d5-bb7b-742671402810
  udp: true
  flow: xtls-rprx-vision
  tls: true
  servername: eu-east-es-1.hanvpn.biz
  client-fingerprint: firefox
  reality-opts:
    public-key: 2yLrSZNVyK-n2NSJuVnkokYlFS4q07OT_CfGrDiTRhY
    short-id: 25b5a7681806bc97
  network: tcp
  _source_name: Бесплатный
  name: Испания 1
- type: vless
  server: 50.7.5.163
  port: 443
  uuid: cd3bb7d9-7df3-4644-ac05-c260990ac277
  udp: true
  encryption: none
  flow: xtls-rprx-vision
  tls: true
  servername: ir-viper.failspace.top
  client-fingerprint: firefox
  alpn:
  - h2
  network: tcp
  _source_name: Бесплатный
  name: Европа 4
- type: vless
  server: 50.7.37.154
  port: 443
  uuid: cd3bb7d9-7df3-4644-ac05-c260990ac277
  udp: true
  encryption: none
  flow: xtls-rprx-vision
  tls: true
  servername: at1.moritech.net
  client-fingerprint: firefox
  alpn:
  - h2
  network: tcp
  _source_name: Бесплатный
  name: Австрия 1
- type: vless
  server: 151.242.168.125
  port: 390
  uuid: 7b363f9c-3df9-4b60-a789-9cd36be0bdfe
  udp: true
  encryption: none
  flow: xtls-rprx-vision
  tls: true
  servername: bowandbead.com
  client-fingerprint: qq
  reality-opts:
    public-key: 5RCgAVjaT7hwdVIKAEULswXGqR127ZOZV6X17nEhYk8
    short-id: b545fe8c5e22f92d
  network: tcp
  _source_name: Бесплатный
  name: Европа 5
- type: vless
  server: 50.7.36.26
  port: 443
  uuid: cd3bb7d9-7df3-4644-ac05-c260990ac277
  udp: true
  encryption: none
  flow: xtls-rprx-vision
  tls: true
  servername: at2.moritech.net
  client-fingerprint: firefox
  alpn:
  - h2
  network: tcp
  _source_name: Бесплатный
  name: Австрия 2
- type: vless
  server: 50.7.226.171
  port: 443
  uuid: cd3bb7d9-7df3-4644-ac05-c260990ac277
  udp: true
  flow: xtls-rprx-vision
  tls: true
  servername: viper-21.moriarty-web.com
  client-fingerprint: firefox
  alpn:
  - h2
  network: tcp
  tcp-opts:
    header:
      type: none
  _source_name: Бесплатный
  name: Европа 6
- type: vless
  server: 194.34.175.195
  port: 443
  uuid: 6429d27e-a7d4-4e04-ae57-e88243fbbfe3
  udp: true
  encryption: none
  flow: xtls-rprx-vision
  tls: true
  servername: localhost
  client-fingerprint: firefox
  reality-opts:
    public-key: F2VfBr2UmjDTErB_oruvW5aIvzH_xGfM2AW5_w-DF0I
  network: tcp
  _source_name: Бесплатный
  name: Канада 3
- type: vless
  server: 194.34.175.223
  port: 443
  uuid: 6429d27e-a7d4-4e04-ae57-e88243fbbfe3
  udp: true
  encryption: none
  flow: xtls-rprx-vision
  tls: true
  servername: localhost
  client-fingerprint: firefox
  reality-opts:
    public-key: F2VfBr2UmjDTErB_oruvW5aIvzH_xGfM2AW5_w-DF0I
  network: tcp
  _source_name: Бесплатный
  name: Канада 4
- type: vless
  server: 50.7.249.178
  port: 443
  uuid: cd3bb7d9-7df3-4644-ac05-c260990ac277
  udp: true
  encryption: none
  flow: xtls-rprx-vision
  tls: true
  servername: pl2-ded.moritech.net
  client-fingerprint: firefox
  alpn:
  - h2
  network: tcp
  _source_name: Бесплатный
  name: Германия 4
- type: vless
  server: 50.7.182.18
  port: 443
  uuid: cd3bb7d9-7df3-4644-ac05-c260990ac277
  udp: true
  encryption: none
  flow: xtls-rprx-vision
  tls: true
  servername: viper-20.moriarty-web.com
  alpn:
  - h2
  network: tcp
  _source_name: Бесплатный
  name: Европа 7
proxy-groups:
- name: 🚀 Freedom Rudy
  type: select
  proxies:
  - Россия 1
  - Финляндия 1
  - Россия 2
  - Европа 1
  - Германия 1
  - Россия 3
  - Германия 2
  - Польша 1
  - Франция 1
  - Канада 1
  - Германия 3
  - Канада 2
  - Европа 2
  - Европа 3
  - Финляндия 2
  - Испания 1
  - Европа 4
  - Австрия 1
  - Европа 5
  - Австрия 2
  - Европа 6
  - Канада 3
  - Канада 4
  - Германия 4
  - Европа 7
  - DIRECT
rules:
- MATCH,🚀 Freedom Rudy
