proxies:
  - name: "🇩🇪 Германия 1 Gabriele Sabatino"
    type: vless
    server: 87.242.95.198
    port: 5443
    uuid: c4854b1a-ec0f-4c5e-940b-f23c8fd39253
    flow: xtls-rprx-vision
    tls: true
    servername: max.ru
    client-fingerprint: firefox
    reality-opts:
      public-key: ZOhyzm2BZ0OsSTfS_zizRo8TlkXopKsyL48KiR76tj0
      short-id: 6f5648b1673b8042
    network: tcp

proxy-groups:
  - name: "🚀 Proxy"
    type: select
    proxies:
      - "🇩🇪 Германия 1 Gabriele Sabatino"
      - DIRECT

rules:
  - MATCH,🚀 Proxy
