name: Update subscription

on:
  workflow_dispatch:

  schedule:
    - cron: "0 */6 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Build config
        run: |
          python build.py

      - name: Download Mihomo
        run: |
          wget -q https://github.com/MetaCubeX/mihomo/releases/download/v1.19.30/mihomo-linux-amd64-v1-v1.19.30.gz
          gunzip mihomo-linux-amd64-v1-v1.19.30.gz
          mv mihomo-linux-amd64-v1-v1.19.30 mihomo
          chmod +x mihomo

      - name: Check proxies
        run: |
          python check.py

      - name: Commit config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add config.yaml

          if git diff --cached --quiet; then
            echo "No changes to config.yaml"
          else
            git commit -m "Update subscription"
            git push
          fi
